services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres.wuaklwmawrgklpyvyolx:bUXo9mMGDE0ixdqA@aws-1-us-east-1.pooler.supabase.com:6543/postgres
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production