apiVersion: apps/v1
kind: Deployment
metadata:
  name: parcial-backend-app
  namespace: parcial-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: parcial-backend-app
  template:
    metadata:
      labels:
        app: parcial-backend-app
    spec:
      containers:
      - name: app
        image: parcial-backend-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DATABASE_URL
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: JWT_SECRET
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5